### ISSUE TITLE
Document all the stonesoup components

### ISSUE THREAD

**Issue by cmoulliard** [konflux-ci/architecture#54]
## TODO

The following components (= links) are not documented at all part of the [book](https://redhat-appstudio.github.io/book/book/index.html) - see section "Service (Component) Context" 

- [x] ~GitOps Service~ (This is likely going to be decomissioned, pending https://github.com/redhat-appstudio/architecture/pull/147)
- [x] Build Service ([updated](https://redhat-appstudio.github.io/architecture/architecture/build-service.html))
- [x] ~Workspace and terminal service~ (This never really became a part of the service).
- [ ] Service provider integration
- [x] HAS ([updated](https://redhat-appstudio.github.io/architecture/architecture/hybrid-application-service.html))
- [x] Java Rebuild Service ([updated](https://redhat-appstudio.github.io/architecture/architecture/jvm-build-service.html))
